import { useParams, Link } from "wouter";
import { ArrowLeft, BookOpen, Clock3, LockKeyhole } from "lucide-react";
import { articles } from "@/lib/sabacn";
import BackButton from "@/components/BackButton";

const articleBody: Record<string, string[]> = {
  "compress-images-without-losing-quality": ["ضغط الصورة لا يعني جعلها ضبابية. الفكرة هي تقليل البيانات التي لا يلاحظها العين مع الحفاظ على الأبعاد المناسبة للاستخدام.", "ابدأ باختيار الصيغة. صور المشاهد والصور الفوتوغرافية غالباً تناسب JPG أو WebP، بينما الرسومات التي تحتاج شفافية تناسب PNG أو WebP بشفافية. بعد ذلك غيّر الأبعاد قبل رفع الجودة؛ صورة بعرض 2400 بكسل ليست ضرورية لكل بطاقة صغيرة.", "استخدم هذه الإرشادات عند تجهيز الصور محلياً، ثم قارن حجم الملف والنتيجة بصرياً. احتفظ بنسخة الأصل خارج الموقع إذا كانت الصورة مهمة، ولا تستبدل الأصل بالنسخة المضغوطة قبل المراجعة."],
  "jpg-png-webp-differences": ["اختيار الصيغة قرار عملي، وليس سباقاً نحو صيغة واحدة. JPG مناسب للصور الفوتوغرافية، PNG مفيد للرسومات والشفافية، وWebP خيار حديث يجمع حجماً جيداً مع دعم للشفافية في أغلب المتصفحات.", "اسأل أولاً: هل أحتاج شفافية؟ هل الصورة فوتوغرافية؟ هل ستعرض على الويب؟ الإجابة تحدد الصيغة أكثر من اسم الأداة المستخدمة.", "جرّب التحويل محلياً ثم افتح الناتج في جهازك. إذا كان الملف سيستخدم في صفحة عامة، أضف نصاً بديلاً يصف الصورة بدلاً من تركه فارغاً."],
  "clean-text-before-publishing": ["النص المنظف أسهل للقراءة والمراجعة. قبل نشر أي فقرة، أزل المسافات المتكررة والأسطر الفارغة، ثم راجع علامات الترقيم والتكرار المعنوي.", "لا تجعل التنظيف آلياً بالكامل. قد تكون الأسطر المتكررة مقصودة في قائمة أو كود. استخدم أي معالجة آلية كخطوة مساعدة ثم اقرأ النتيجة كاملة.", "تساعدك المراجعة المنظمة على إزالة المشكلات الشكلية، بينما تبقى القراءة البشرية ضرورية للتأكد من المعنى والدقة."],
  "seo-title-description-guide": ["العنوان الجيد يشرح الصفحة للقارئ قبل محرك البحث. اجعله محدداً، واذكر الفائدة الأساسية دون وعود مبالغ فيها أو تكرار كلمات مفتاحية.", "الوصف ليس مكاناً لحشو الكلمات. اكتب جملة أو جملتين تشرحان ما سيجده الزائر، ثم راجع الطول حتى لا يصبح النص مقطوعاً في نتائج البحث.", "استخدم العنوان والوصف كملخص صادق للمحتوى، وتأكد من أن الصفحة تفي بالوعد الموجود فيهما."],
  "json-validation-for-beginners": ["JSON صيغة نصية بسيطة لتبادل البيانات، لكنها حساسة للفواصل والاقتباسات. كل مفتاح يجب أن يكون بين علامتي اقتباس، ولا تُستخدم فاصلة بعد آخر عنصر.", "عندما يفشل التحقق، ابدأ من مكان الخطأ الذي يظهره المحرر. افحص الأقواس المتطابقة ثم الفواصل ثم القيم النصية. لا تحاول إصلاح الملف كله دفعة واحدة.", "قسّم البيانات إلى أجزاء صغيرة أثناء المراجعة، واحفظ نسخة من الملف قبل التعديلات المهمة."],
  "privacy-first-browser-tools": ["المعالجة المحلية تعني أن الملف أو النص يُعالج داخل المتصفح على جهازك بدلاً من رفعه إلى خادم. هذا يقلل سطح مشاركة البيانات، لكنه لا يلغي مسؤولية الاحتفاظ بنسخة آمنة من الملفات المهمة.", "توضح كل ميزة في SABACUN ما إذا كانت المعالجة محلية. لا نطلب التسجيل للمحتوى الأساسي، ولا نحتاج إلى معرفة محتوى الملف كي تعمل معالجة محلية مستقبلية داخل المتصفح.", "إذا كانت الخدمة تحتاج مستقبلاً إلى معالجة خادمية، يجب أن تعرض ذلك بوضوح وتحدد نوع البيانات ومدة الاحتفاظ بها قبل أن يختار المستخدم المتابعة."]
};

export default function Knowledge() {
  const { slug } = useParams<{ slug?: string }>();
  const article = slug ? articles.find((item) => item.slug === slug) : undefined;
  if (slug && article) return <Article article={article} />;
  return <div className="min-h-screen bg-[#f7f8f4]"><div className="mx-auto max-w-7xl px-4 py-14 lg:px-8"><div className="flex items-center justify-between"><Link href="/" className="font-display text-sm font-bold tracking-[.2em] text-[#1c615d]">SABACUN</Link><BackButton fallback="/" label="الرئيسية" /></div><div className="mt-8 max-w-3xl"><div className="mb-4 inline-flex items-center gap-2 rounded-full bg-[#edf5ef] px-3 py-2 text-xs font-bold text-[#1c615d]"><BookOpen size={15} /> مركز معرفة عربي</div><h1 className="text-4xl font-bold leading-tight text-[#123f45]">شروحات تساعدك على إنجاز المهمة</h1><p className="mt-4 leading-8 text-[#687a7d]">مقالات عملية قصيرة، مكتوبة لتجيب عن سؤال حقيقي وتشرح الفكرة بوضوح.</p></div><div className="mt-12 grid gap-5 md:grid-cols-2 lg:grid-cols-3">{articles.map((item) => <Link key={item.slug} href={`/knowledge/${item.slug}`} className="tool-card focus-ring rounded-3xl border bg-white p-6"><div className="mb-7 flex items-center justify-between text-xs font-bold"><span className="text-[#1c615d]">{item.category}</span><span className="inline-flex items-center gap-1 text-[#819092]"><Clock3 size={14} />{item.readTime}</span></div><h2 className="text-xl font-bold leading-8 text-[#173238]">{item.title}</h2><p className="mt-3 leading-7 text-[#687a7d]">{item.excerpt}</p><span className="mt-6 inline-flex items-center gap-2 text-sm font-bold text-[#1c615d]">قراءة المقال <ArrowLeft size={16} /></span></Link>)}</div></div></div>;
}

function Article({ article }: { article: (typeof articles)[number] }) {
  const paragraphs = articleBody[article.slug] || [];
  return <div className="min-h-screen bg-[#f7f8f4]"><article className="mx-auto max-w-4xl px-4 py-14 lg:px-8"><BackButton fallback="/knowledge" label="مركز المعرفة" /><div className="mt-10"><span className="text-sm font-bold text-[#c38d26]">{article.category} · {article.readTime}</span><h1 className="mt-3 text-4xl font-bold leading-[1.3] text-[#123f45] sm:text-5xl">{article.title}</h1><p className="mt-6 text-lg leading-9 text-[#687a7d]">{article.excerpt}</p></div><div className="mt-12 rounded-[2rem] border bg-white p-6 sm:p-10"><div className="mb-8 flex items-center gap-3 rounded-2xl bg-[#edf5ef] p-4 text-sm leading-7 text-[#557174]"><LockKeyhole className="shrink-0 text-[#1c615d]" size={19} />هذا المقال أصلي ومكتوب لمساعدة القارئ، ولا يعتمد على إعادة نشر RSS أو نسخ من مواقع أخرى.</div>{paragraphs.map((paragraph) => <p key={paragraph} className="mb-6 text-lg leading-[2.1] text-[#344d51]">{paragraph}</p>)}</div></article></div>;
}
