import { Link, useParams } from "wouter";
import BackButton from "@/components/BackButton";

export const WHATSAPP_BUSINESS_NUMBER = "9647740669189";
export const OFFICIAL_EMAIL = "alihkime20@gmail.com";
export const WHATSAPP_BUSINESS_URL = `https://wa.me/${WHATSAPP_BUSINESS_NUMBER}`;
export const CONTACT_PAGE_TITLE = "اتصل بنا";
export const CONTACT_PAGE_INTRO = "نحن هنا لخدمة المجتمع ودعم مبادرات التطوع والتبرع. نرحب برسائلكم واقتراحاتكم وبلاغاتكم عبر واتساب أو البريد الإلكتروني.";
export const CONTACT_WHATSAPP_SECTION_TITLE = "واتساب الأعمال";
export const EDITORIAL_LEAD = "مهندس علي";

const pages = {
  about: { title: "من نحن", intro: `SABACUN مبادرة مجتمعية عربية تجمع الناس حول فرص التطوع وطلبات التبرع بالدم، وتديرها ${EDITORIAL_LEAD} بهدف تسهيل الوصول إلى المبادرات ذات الأثر.`, sections: [{ h: "رسالتنا", p: "نساعد أفراد المجتمع على اكتشاف فرص التطوع وطلبات التبرع بالدم ونشر المبادرات المحلية بوضوح ومسؤولية. نؤمن بأن مشاركة بسيطة قد تصنع فرقاً حقيقياً في حياة إنسان أو في محيط كامل." }, { h: "كيف نعمل؟", p: "نوفّر مساحة منظمة لعرض الحملات، ونعمل على إبقاء المعلومات سهلة الفهم ومباشرة. يمكن للزائر تصفح المبادرات، تسجيل مشاركته، أو نشر حملة جديدة ليطلع عليها أفراد المجتمع." }, { h: "مبادئنا", p: "نحترم خصوصية المشاركين، ونسعى إلى وضوح بيانات كل حملة، ونشجع التواصل المسؤول والتحقق من التفاصيل قبل المشاركة. SABACUN مساحة للتنسيق المجتمعي وليست بديلاً عن الجهات الصحية أو المؤسسات الرسمية." }] },
  privacy: { title: "سياسة الخصوصية", intro: "نحترم خصوصية كل من يزور SABACUN أو يشارك في مبادراتها المجتمعية.", sections: [{ h: "بيانات الحملات والمشاركة", p: "قد تظهر في الحملة المعلومات التي يضيفها ناشرها، مثل نوع المبادرة ووصفها والموقع والتاريخ ووسيلة التواصل. استخدموا المعلومات اللازمة فقط، وتجنبوا نشر أرقام الهوية أو البيانات الطبية أو أي معلومات حساسة على صفحات عامة." }, { h: "التواصل والبيانات التقنية", p: "قد نحتفظ برسائل التواصل أو البيانات التقنية الأساسية اللازمة لتشغيل الموقع وحمايته، مثل نوع المتصفح ووقت الزيارة ومسار الصفحة. لا نبيع بيانات المستخدمين ولا نستخدم بيانات المشاركين لأغراض لا ترتبط بتشغيل المبادرة." }, { h: "التبرع بالدم والمسؤولية الصحية", p: "SABACUN مساحة للتنسيق المجتمعي وليست جهة طبية. لا نطلب تشخيصاً أو ملفاً طبياً، ويجب توجيه الأسئلة الصحية والتحقق من أهلية التبرع إلى بنك الدم أو الجهة الصحية المختصة." }, { h: "الروابط الخارجية", p: "قد تتضمن الحملات وسائل تواصل أو روابط لجهات خارجية. تحقق من الجهة قبل مشاركة أي بيانات، وراجع سياسة الخصوصية الخاصة بها." }] },
  terms: { title: "شروط الاستخدام", intro: "باستخدام SABACUN توافق على المشاركة والنشر بطريقة قانونية ومحترمة ومسؤولة.", sections: [{ h: "استخدام المبادرة", p: "استخدم الموقع للتطوع والتنسيق لطلبات التبرع بالدم ونشر المبادرات النافعة. يحظر نشر معلومات مضللة أو محتوى مسيء أو طلبات مجهولة أو أي محتوى ينتهك حقوق الآخرين." }, { h: "مسؤولية ناشر الحملة", p: "يتحمل ناشر كل حملة مسؤولية دقة المعلومات التي يقدمها وتحديثها والتواصل مع المشاركين. لا تضع بيانات طبية أو شخصية حساسة في الوصف العام، وتحقق من التفاصيل قبل الحضور أو المشاركة." }, { h: "حدود المنصة", p: "SABACUN منصة للتنسيق المجتمعي وليست جهة طبية أو جهة اعتماد أو بديلاً عن المؤسسات الرسمية. لا تضمن المنصة نتيجة أي حملة، ويجب الرجوع إلى الجهات المختصة في المسائل الصحية." }] },
  cookies: { title: "سياسة ملفات الارتباط", intro: "نستخدم الحد الأدنى من ملفات الارتباط اللازمة لتشغيل SABACUN وتذكر اختيارك المتعلق بالخصوصية.", sections: [{ h: "اختيارك", p: "يمكنك قبول أو رفض ملفات الارتباط غير الضرورية من إشعار الخصوصية. يمكنك حذف الملفات من إعدادات المتصفح في أي وقت، ولن يمنع ذلك تصفح المبادرات الأساسية." }, { h: "الغرض منها", p: "قد تُستخدم الملفات الأساسية لحفظ تفضيل الخصوصية وتشغيل الجلسة بصورة سليمة. لا نستخدمها لتتبع المشاركين أو لإجبارهم على التسجيل." }] },
  content: { title: "سياسة المحتوى", intro: "نحافظ على محتوى مجتمعي واضح يساعد الناس على التطوع والتبرع والتواصل المسؤول.", sections: [{ h: "المحتوى المقبول", p: "يجب أن تكون المنشورات مرتبطة بمبادرة مجتمعية أو فرصة تطوع أو طلب تبرع بالدم، وأن تتضمن معلومات واضحة قابلة للتحقق. يمنع نشر خطاب الكراهية أو الاحتيال أو الإعلانات المضللة أو البيانات الحساسة." }, { h: "التبليغ والتحديث", p: "إذا وجدت حملة منتهية أو معلومة غير دقيقة أو محتوى مخالفاً، تواصل معنا مع رابط الصفحة ووصف المشكلة. نراجع البلاغ ونسعى إلى تصحيح المحتوى أو تحديثه عند الحاجة." }] },
  contact: { title: CONTACT_PAGE_TITLE, intro: CONTACT_PAGE_INTRO, sections: [{ h: "للاستفسارات والاقتراحات", p: `للتعاون أو اقتراح مبادرة أو الإبلاغ عن حملة تحتاج إلى تحديث، راسلنا عبر البريد الرسمي: ${OFFICIAL_EMAIL}` }, { h: CONTACT_WHATSAPP_SECTION_TITLE, p: `للتواصل السريع بشأن المبادرات والمشاركة، استخدم واتساب الأعمال على الرقم: ${WHATSAPP_BUSINESS_NUMBER}` }, { h: "معلومات مهمة عند التواصل", p: "اذكر اسم الحملة ورابطها وسبب رسالتك بوضوح. لا ترسل كلمات مرور أو أرقام هويات أو تقارير طبية أو ملفات شخصية حساسة." }] },
} as const;

export type LegalPageKey = keyof typeof pages;

export default function LegalPage({ page: requestedPage }: { page?: LegalPageKey }) {
  const { page: routePage = "about" } = useParams<{ page: LegalPageKey }>();
  const page = requestedPage ?? routePage;
  const data = pages[page as LegalPageKey] ?? pages.about;
  return <div dir="rtl" className="min-h-screen bg-[#f7f8f4] text-[#384448]"><header className="border-b bg-white/80"><div className="mx-auto flex max-w-4xl items-center justify-between px-5 py-5"><Link href="/" className="font-display text-2xl font-bold tracking-wide text-[#123f45]">SABACUN</Link><BackButton fallback="/" label="الرئيسية" /></div></header><main className="mx-auto max-w-3xl px-5 py-14"><span className="text-xs font-bold tracking-[.16em] text-[#c38d26]">SABACUN / سياسة واضحة</span><h1 className="mt-3 text-4xl font-bold text-[#123f45] md:text-5xl">{data.title}</h1><p className="mt-7 rounded-2xl border-r-4 border-[#d9a947] bg-white px-5 py-4 text-lg leading-9">{data.intro}</p><div className="mt-10 space-y-8">{data.sections.map((section) => <section key={section.h}><h2 className="text-2xl font-bold text-[#123f45]">{section.h}</h2><p className="mt-3 leading-9">{section.p}</p></section>)}</div>{page === "contact" && <div className="mt-10 rounded-3xl border bg-white p-6"><a href={`mailto:${OFFICIAL_EMAIL}`} className="mb-3 inline-flex w-full items-center justify-center rounded-full border border-[#123f45] px-6 py-4 text-sm font-bold text-[#123f45]">مراسلة البريد الرسمي</a><a href={WHATSAPP_BUSINESS_URL} target="_blank" rel="noreferrer" className="inline-flex w-full items-center justify-center rounded-full bg-[#138c5b] px-6 py-4 text-sm font-bold text-white">مراسلة واتساب الأعمال</a></div>}<p className="mt-12 border-t pt-5 text-xs leading-7 text-[#7a8383]">هذه الصفحة معلومات عامة للموقع، ويتم تحديثها عند إضافة أدوات أو خدمات جديدة.</p></main></div>;
}
