import { Link, useParams } from "wouter";
import BackButton from "@/components/BackButton";

export const WHATSAPP_BUSINESS_NUMBER = "9647740669189";
export const OFFICIAL_EMAIL = "alihkime20@gmail.com";
export const WHATSAPP_BUSINESS_URL = `https://wa.me/${WHATSAPP_BUSINESS_NUMBER}`;
export const CONTACT_PAGE_TITLE = "اتصل بنا";
export const CONTACT_PAGE_INTRO = "نرحب بالملاحظات التي تساعدنا على جعل الأدوات أوضح وأكثر فائدة. واتساب الأعمال والبريد الرسمي متاحان للتواصل.";
export const CONTACT_WHATSAPP_SECTION_TITLE = "واتساب الأعمال";
export const EDITORIAL_LEAD = "مهندس علي";

const pages = {
  about: { title: "من نحن", intro: `SABACUN منصة عربية للأدوات الرقمية المجانية ومركز معرفة عملي، أسسها ويديرها ${EDITORIAL_LEAD}.`, sections: [{ h: "ما الذي نقدمه؟", p: "نبني أدوات صغيرة واضحة تساعد على إنجاز مهام الصور والنصوص وملفات PDF وSEO والتقنية من دون تعقيد غير ضروري. الاسم والهوية مستلهمان بخفة من تاريخ العراق، أما المنتج فهو منصة تقنية حديثة." }, { h: "الجهة المسؤولة", p: `يدير ${EDITORIAL_LEAD} هوية SABACUN ومحتواها التوضيحي، ويتابع تحديث الشروحات وتصحيح الأخطاء الواضحة. يمكن إرسال الملاحظات والاقتراحات عبر البريد الرسمي أو واتساب الأعمال في صفحة التواصل.` }, { h: "مبادئنا", p: "نركز على الفائدة قبل الإعلانات، والوضوح قبل المبالغة، والخصوصية قبل جمع البيانات. نكتب الشروحات العربية المرتبطة بالأدوات لأن القارئ يحتاج إلى فهم القرار، لا مجرد زر تنفيذ." }] },
  privacy: { title: "سياسة الخصوصية", intro: "نشرح هنا ما يحدث عند استخدام SABACUN بطريقة مباشرة.", sections: [{ h: "المعالجة داخل المتصفح", p: "تتم معالجة الصور والنصوص في الأدوات المحلية داخل متصفحك قدر الإمكان. لا نحتاج إلى رفع الملف أو معرفة محتواه كي تعمل هذه العمليات. قد يحتفظ المتصفح ببيانات مؤقتة أثناء الجلسة، ويمكنك حذفها من إعدادات المتصفح." }, { h: "البيانات التقنية والتحليلات", p: "قد تُسجل بيانات تقنية أساسية لتشغيل الموقع وحمايته، مثل نوع المتصفح والوقت ومسار الصفحة. لا نطلب التسجيل لاستخدام الأدوات الأساسية، ولا نبيع بيانات المستخدمين. لا تُحمّل التحليلات غير الضرورية قبل اختيار المستخدم من إشعار الموافقة." }, { h: "الروابط الخارجية", p: "قد تتضمن المقالات روابط إلى أدوات أو مصادر خارجية. راجع سياسة الموقع الخارجي قبل إدخال بيانات حساسة فيه؛ مسؤولية SABACUN تقتصر على الصفحات التي نديرها." }] },
  terms: { title: "شروط الاستخدام", intro: "باستخدام SABACUN توافق على استخدام الأدوات بطريقة قانونية ومسؤولة.", sections: [{ h: "الاستخدام المقبول", p: "لا تستخدم الموقع لمعالجة ملفات ضارة أو انتهاك حقوق الآخرين أو التحايل على أنظمة الحماية. أنت مسؤول عن امتلاك الحق في استخدام أي ملف تدخله في أداة محلية." }, { h: "طبيعة الأدوات", p: "الأدوات مجانية وتقدم للمساعدة العامة. راجع النتيجة قبل استخدامها في قرار تجاري أو تقني مهم، واحتفظ بنسخة أصلية من الملفات المهمة." }] },
  cookies: { title: "سياسة ملفات الارتباط", intro: "نستخدم الحد الأدنى اللازم لتذكر اختيارات الخصوصية وتحسين تشغيل الموقع.", sections: [{ h: "الاختيار", p: "يمكنك قبول أو رفض ملفات الارتباط غير الضرورية من إشعار الخصوصية. لا ينبغي تحميل التحليلات غير الضرورية قبل اختيارك. يمكنك حذف الملفات من إعدادات المتصفح في أي وقت." }, { h: "لماذا نستخدمها؟", p: "قد نحتاج إلى ملفات أساسية لحفظ تفضيل اللغة أو الموافقة. لا نستخدم الإشعار لإخفاء المحتوى أو إجبارك على التسجيل." }] },
  content: { title: "سياسة المحتوى", intro: "نكتب محتوى SABACUN لمساعدة المستخدم، لا لملء الصفحات أو نسخ مواقع أخرى.", sections: [{ h: "الأصالة والقيمة", p: "لا يعتمد مركز المعرفة على إعادة نشر RSS أو نسخ المقالات. كل شرح مرتبط بأداة أو سؤال عملي، ونراجع النصوص قبل نشرها ونحدثها عندما تتغير طريقة الاستخدام." }, { h: "التصحيح والتواصل", p: "إذا وجدت خطأً أو شرحاً غير واضح، تواصل معنا مع رابط الصفحة ووصف المشكلة. نراجع البلاغ ونصحح المحتوى عندما يتأكد الخطأ." }] },
  contact: { title: CONTACT_PAGE_TITLE, intro: CONTACT_PAGE_INTRO, sections: [{ h: "البريد الإلكتروني", p: `للاقتراحات أو الإبلاغ عن مشكلة: ${OFFICIAL_EMAIL}` }, { h: CONTACT_WHATSAPP_SECTION_TITLE, p: `يمكنك التواصل عبر واتساب الأعمال على الرقم: ${WHATSAPP_BUSINESS_NUMBER}` }, { h: "ماذا ترسل؟", p: "اذكر اسم الأداة، الجهاز أو المتصفح، والخطوات التي أدت إلى المشكلة. لا ترسل ملفات شخصية أو كلمات مرور." }] },
} as const;

export type LegalPageKey = keyof typeof pages;

export default function LegalPage({ page: requestedPage }: { page?: LegalPageKey }) {
  const { page: routePage = "about" } = useParams<{ page: LegalPageKey }>();
  const page = requestedPage ?? routePage;
  const data = pages[page as LegalPageKey] ?? pages.about;
  return <div dir="rtl" className="min-h-screen bg-[#f7f8f4] text-[#384448]"><header className="border-b bg-white/80"><div className="mx-auto flex max-w-4xl items-center justify-between px-5 py-5"><Link href="/" className="font-display text-2xl font-bold tracking-wide text-[#123f45]">SABACUN</Link><BackButton fallback="/" label="الرئيسية" /></div></header><main className="mx-auto max-w-3xl px-5 py-14"><span className="text-xs font-bold tracking-[.16em] text-[#c38d26]">SABACUN / سياسة واضحة</span><h1 className="mt-3 text-4xl font-bold text-[#123f45] md:text-5xl">{data.title}</h1><p className="mt-7 rounded-2xl border-r-4 border-[#d9a947] bg-white px-5 py-4 text-lg leading-9">{data.intro}</p><div className="mt-10 space-y-8">{data.sections.map((section) => <section key={section.h}><h2 className="text-2xl font-bold text-[#123f45]">{section.h}</h2><p className="mt-3 leading-9">{section.p}</p></section>)}</div>{page === "contact" && <div className="mt-10 rounded-3xl border bg-white p-6"><a href={`mailto:${OFFICIAL_EMAIL}`} className="mb-3 inline-flex w-full items-center justify-center rounded-full border border-[#123f45] px-6 py-4 text-sm font-bold text-[#123f45]">مراسلة البريد الرسمي</a><a href={WHATSAPP_BUSINESS_URL} target="_blank" rel="noreferrer" className="inline-flex w-full items-center justify-center rounded-full bg-[#138c5b] px-6 py-4 text-sm font-bold text-white">مراسلة واتساب الأعمال</a></div>}<p className="mt-12 border-t pt-5 text-xs leading-7 text-[#7a8383]">هذه الصفحة معلومات عامة للموقع، ويتم تحديثها عند إضافة أدوات أو خدمات جديدة.</p></main></div>;
}
