import { useMemo, useState } from "react";
import { Link } from "wouter";
import { ArrowLeft, Search } from "lucide-react";
import { categories, tools, type ToolCategory } from "@/lib/sabacn";
import BackButton from "@/components/BackButton";

export default function Tools() {
  const initial = new URLSearchParams(window.location.search).get("category") as ToolCategory | null;
  const [category, setCategory] = useState<ToolCategory>(initial && categories.some((item) => item.name === initial) ? initial : "الكل");
  const [query, setQuery] = useState("");
  const filtered = useMemo(() => tools.filter((tool) => (category === "الكل" || tool.category === category) && (!query || `${tool.name} ${tool.description} ${tool.tags.join(" ")}`.toLowerCase().includes(query.toLowerCase()))), [category, query]);
  return <div className="min-h-screen bg-[#f7f8f4]"><div className="mx-auto max-w-7xl px-4 py-12 lg:px-8"><div className="mb-10 flex flex-col gap-5 md:flex-row md:items-end md:justify-between"><div><Link href="/" className="font-display text-sm font-bold tracking-[.2em] text-[#1c615d]">SABACUN</Link><h1 className="mt-3 text-4xl font-bold text-[#123f45]">جميع الأدوات</h1><p className="mt-3 max-w-2xl leading-8 text-[#687a7d]">أدوات مجانية عملية للصور والنصوص وPDF وSEO والتطوير، تعمل مباشرة من المتصفح عندما يكون ذلك ممكناً.</p></div><BackButton fallback="/" /></div><div className="mb-8 flex flex-col gap-3 md:flex-row"><div className="relative flex-1"><Search className="absolute right-4 top-1/2 -translate-y-1/2 text-[#789094]" size={20} /><input value={query} onChange={(e) => setQuery(e.target.value)} placeholder="ابحث باسم الأداة أو وظيفتها" className="focus-ring w-full rounded-2xl border bg-white px-12 py-4 outline-none" /></div><div className="flex gap-2 overflow-x-auto pb-1">{categories.map(({ name }) => <button key={name} onClick={() => setCategory(name)} className={`focus-ring whitespace-nowrap rounded-xl px-4 py-3 text-sm font-bold ${category === name ? "bg-[#123f45] text-white" : "border bg-white text-[#607175]"}`}>{name}</button>)}</div></div><p className="mb-5 text-sm text-[#819092]">عرض {filtered.length} أداة</p><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{filtered.map((tool) => { const Icon = tool.icon; return <Link key={tool.slug} href={`/tool/${tool.slug}`} className="tool-card focus-ring rounded-3xl border bg-white p-6"><div className="mb-8 flex items-start justify-between"><span className="flex h-12 w-12 items-center justify-center rounded-2xl bg-[#edf5ef] text-[#1c615d]"><Icon size={23} /></span><span className="rounded-full bg-[#f4f7f4] px-3 py-1 text-xs font-bold text-[#718084]">{tool.category}</span></div><h2 className="text-xl font-bold text-[#173238]">{tool.name}</h2><p className="mt-3 min-h-[54px] leading-7 text-[#687a7d]">{tool.description}</p><div className="mt-6 flex items-center gap-2 text-sm font-bold text-[#1c615d]">فتح الأداة <ArrowLeft size={16} /></div></Link>; })}</div></div></div>;
}
