import { useMemo, useRef, useState } from "react";
import { Link, useParams } from "wouter";
import { Check, Copy, Download, FileImage, Info, LockKeyhole, Palette, RefreshCw, Upload, WandSparkles } from "lucide-react";
import { findTool } from "@/lib/sabacn";
import BackButton from "@/components/BackButton";
import { jsPDF } from "jspdf";

const download = (blob: Blob, name: string) => { const url = URL.createObjectURL(blob); const a = document.createElement("a"); a.href = url; a.download = name; a.click(); URL.revokeObjectURL(url); };
const slugify = (value: string) => value.trim().toLowerCase().replace(/[أإآ]/g, "ا").replace(/ة/g, "ه").replace(/ى/g, "ي").replace(/[^\w\u0600-\u06ff\s-]/g, "").replace(/[\s_]+/g, "-").replace(/-+/g, "-");

export default function ToolPage() {
  const { slug = "" } = useParams<{ slug: string }>();
  const tool = findTool(slug);
  if (!tool) return <div className="mx-auto max-w-3xl px-4 py-24 text-center"><h1 className="text-3xl font-bold text-[#123f45]">الأداة غير موجودة</h1><Link href="/tools" className="mt-6 inline-flex text-[#1c615d]">العودة إلى الأدوات</Link></div>;
  return <div className="min-h-screen bg-[#f7f8f4]"><div className="mx-auto max-w-5xl px-4 py-10 lg:px-8"><BackButton fallback="/tools" label="جميع الأدوات" /><div className="mt-8 grid gap-8 lg:grid-cols-[1.1fr_.9fr]"><section><div className="mb-7 flex items-start gap-4"><span className="flex h-14 w-14 shrink-0 items-center justify-center rounded-2xl bg-[#123f45] text-[#f4d384]"><tool.icon size={26} /></span><div><span className="text-sm font-bold text-[#c38d26]">{tool.category}</span><h1 className="mt-1 text-4xl font-bold text-[#123f45]">{tool.name}</h1><p className="mt-3 leading-8 text-[#687a7d]">{tool.description}</p></div></div><div className="rounded-3xl border bg-white p-5 shadow-[0_16px_40px_rgba(20,37,43,.06)]"><ToolWorkspace slug={slug} /></div></section><aside className="space-y-5"><InfoCard title="طريقة الاستخدام" items={["أدخل النص أو اختر الملف المطلوب.", "عدّل الخيارات ثم شغّل الأداة.", "نزّل النتيجة أو انسخها إلى مشروعك."]} /><div className="rounded-3xl border border-[#cce2d2] bg-[#edf5ef] p-5"><div className="mb-3 flex items-center gap-2 font-bold text-[#1c615d]"><LockKeyhole size={18} /> الخصوصية أولاً</div><p className="text-sm leading-7 text-[#557174]">تتم معالجة هذه الأداة داخل المتصفح قدر الإمكان. لا نطلب إنشاء حساب ولا نرفع النصوص أو الصور إلى خادم.</p></div><InfoCard title="متى تستخدمها؟" items={["للمهام اليومية السريعة.", "قبل نشر محتوى أو ملف على الويب.", "عندما تريد إنجاز المهمة دون تثبيت برنامج."]} /></aside></div><div className="mt-12 border-t pt-8"><h2 className="text-2xl font-bold text-[#123f45]">نصيحة SABACUN</h2><p className="mt-3 max-w-3xl leading-8 text-[#687a7d]">تحقق من الناتج قبل استخدامه في مشروع إنتاجي، خصوصاً عند التعامل مع ملفات مهمة. الأدوات هنا مصممة لتقليل الخطوات، مع إبقاء القرار النهائي للمستخدم.</p></div></div></div>;
}

function InfoCard({ title, items }: { title: string; items: string[] }) { return <div className="rounded-3xl border bg-white p-5"><h2 className="mb-4 font-bold text-[#173238]">{title}</h2><div className="grid gap-3">{items.map((item) => <div key={item} className="flex gap-2 text-sm leading-6 text-[#687a7d]"><Check size={16} className="mt-1 shrink-0 text-[#1c615d]" />{item}</div>)}</div></div>; }

function ToolWorkspace({ slug }: { slug: string }) {
  const [value, setValue] = useState(""); const [second, setSecond] = useState(""); const [output, setOutput] = useState(""); const [copied, setCopied] = useState(false); const [fileName, setFileName] = useState(""); const [imageUrl, setImageUrl] = useState(""); const [imageError, setImageError] = useState(""); const [quality, setQuality] = useState(0.8); const [width, setWidth] = useState(0); const [height, setHeight] = useState(0); const fileRef = useRef<HTMLInputElement>(null);
  const copy = async () => { await navigator.clipboard?.writeText(output); setCopied(true); setTimeout(() => setCopied(false), 1500); };
  const runText = () => { let result = value; if (slug === "text-counter") result = `الكلمات: ${value.trim() ? value.trim().split(/\s+/).length : 0}\nالحروف: ${value.replace(/\s/g, "").length}\nالجمل: ${value.split(/[.!؟؟]+/).filter(Boolean).length}\nالأسطر: ${value ? value.split(/\n/).length : 0}`; if (slug === "text-cleaner") result = value.replace(/[ \t]+/g, " ").replace(/\n{3,}/g, "\n\n").split("\n").filter((line, index, all) => line.trim() && all.indexOf(line) === index).join("\n").trim(); if (slug === "text-compare") result = value === second ? "لا يوجد اختلاف بين النصين." : `النصان مختلفان.\n\nالنص الأول: ${value.length} حرفاً\nالنص الثاني: ${second.length} حرفاً`; if (slug === "link-extractor") result = (value.match(/https?:\/\/[^\s]+/g) || []).join("\n") || "لم يتم العثور على روابط."; if (slug === "slug-generator") result = slugify(value); if (slug === "json-formatter") { try { result = JSON.stringify(JSON.parse(value), null, 2); } catch { result = "JSON غير صالح: تحقق من الأقواس والفواصل والاقتباسات."; } } if (slug === "meta-checker") result = `طول العنوان: ${value.length} حرفاً\nطول الوصف: ${second.length} حرفاً\n\n${value.length >= 30 && value.length <= 60 ? "العنوان ضمن نطاق عملي." : "راجع طول العنوان ليكون واضحاً ومختصراً."}\n${second.length >= 70 && second.length <= 160 ? "الوصف ضمن نطاق عملي." : "راجع طول الوصف ليشرح الصفحة بوضوح."}`; if (slug === "robots-generator") result = `User-agent: *\nAllow: /\nDisallow: /api/\nSitemap: https://example.com/sitemap.xml`; if (slug === "color-converter") { const hex = value.replace("#", ""); const r = parseInt(hex.slice(0,2),16), g = parseInt(hex.slice(2,4),16), b = parseInt(hex.slice(4,6),16); result = Number.isNaN(r) ? "أدخل HEX صالحاً مثل #123f45" : `RGB: rgb(${r}, ${g}, ${b})\nHEX: #${hex}`; } setOutput(result); };
  const randomPassword = () => { const chars = "ABCDEFGHJKLMNPQRSTUVWXYZabcdefghijkmnopqrstuvwxyz23456789!@#$%"; const bytes = crypto.getRandomValues(new Uint32Array(18)); setOutput(Array.from(bytes, (n) => chars[n % chars.length]).join("")); };
  const randomUuid = () => setOutput(crypto.randomUUID());
  const handleImage = (file?: File) => { setImageError(""); if (!file) return; if (!file.type.startsWith("image/")) { setImageError("يرجى اختيار ملف صورة بصيغة JPG أو PNG أو WebP."); return; } if (file.size > 10 * 1024 * 1024) { setImageError("حجم الصورة يتجاوز الحد المسموح وهو 10 ميغابايت. اختر صورة أصغر."); return; } setFileName(file.name); const url = URL.createObjectURL(file); setImageUrl(url); const img = new Image(); img.onload = () => { setWidth(img.width); setHeight(img.height); }; img.src = url; };
  const processImage = (format: "image/webp" | "image/jpeg" | "image/png" = "image/webp") => { if (!imageUrl) return; const img = new Image(); img.onload = () => { const targetWidth = slug === "image-resizer" && width > 0 ? width : img.width; const targetHeight = slug === "image-resizer" && height > 0 ? height : img.height; const canvas = document.createElement("canvas"); canvas.width = targetWidth; canvas.height = targetHeight; const ctx = canvas.getContext("2d"); if (!ctx) return; ctx.drawImage(img, 0, 0, targetWidth, targetHeight); canvas.toBlob((blob) => blob && download(blob, `${fileName.replace(/\.[^.]+$/, "")}.${format.split("/")[1]}`), format, quality); }; img.src = imageUrl; };
  const processPdf = () => { if (!imageUrl) return; const img = new Image(); img.onload = () => { const orientation = img.width >= img.height ? "landscape" : "portrait"; const pdf = new jsPDF({ orientation, unit: "px", format: [img.width, img.height] }); pdf.addImage(img, "JPEG", 0, 0, img.width, img.height, undefined, "FAST"); pdf.save(`${fileName.replace(/\.[^.]+$/, "") || "sabacun-image"}.pdf`); }; img.src = imageUrl; };
  const extractColor = () => { if (!imageUrl) return; const img = new Image(); img.onload = () => { const canvas = document.createElement("canvas"); canvas.width = 1; canvas.height = 1; const ctx = canvas.getContext("2d"); if (!ctx) return; ctx.drawImage(img, 0, 0, 1, 1); const pixel = ctx.getImageData(0, 0, 1, 1).data; const r = pixel[0]; const g = pixel[1]; const b = pixel[2]; const hex = `#${[r, g, b].map((n) => n.toString(16).padStart(2, "0")).join("")}`; setOutput(`اللون المسيطر التقريبي: ${hex}\nRGB: rgb(${r}, ${g}, ${b})`); }; img.src = imageUrl; };
  if (slug === "pdf-jpg") return <div className="grid gap-5"><div onDrop={(e) => { e.preventDefault(); handleImage(e.dataTransfer.files[0]); }} onDragOver={(e) => e.preventDefault()} className="flex min-h-48 cursor-pointer flex-col items-center justify-center rounded-2xl border-2 border-dashed border-[#cce2d2] bg-[#f7fbf7] p-6 text-center" onClick={() => fileRef.current?.click()}><Upload className="mb-3 text-[#1c615d]" /><p className="font-bold text-[#173238]">اختر صورة لإنشاء ملف PDF</p><p className="mt-2 text-sm text-[#789094]">تتم العملية داخل المتصفح دون رفع الصورة</p><input ref={fileRef} type="file" accept="image/jpeg,image/png,image/webp" className="hidden" onChange={(e) => handleImage(e.target.files?.[0])} />{fileName && <p className="mt-4 text-sm font-bold text-[#1c615d]">{fileName}</p>}{imageError && <p role="alert" className="mt-3 text-sm font-bold text-red-700">{imageError}</p>}</div>{imageUrl && <img src={imageUrl} alt="معاينة الصورة قبل تحويلها إلى PDF" className="max-h-64 w-full rounded-2xl object-contain" />}<div className="flex flex-wrap gap-3"><button onClick={processPdf} disabled={!imageUrl} className="focus-ring inline-flex items-center gap-2 rounded-xl bg-[#123f45] px-5 py-3 font-bold text-white disabled:cursor-not-allowed disabled:opacity-50"><Download size={17} /> إنشاء وتنزيل PDF</button><button onClick={() => { setImageUrl(""); setFileName(""); }} className="focus-ring rounded-xl border px-5 py-3 font-bold text-[#607175]">إزالة</button></div></div>;
  const isImage = slug.includes("image") || slug === "jpg-to-png" || slug === "color-extractor";
  if (isImage) return <div className="grid gap-5"><div onDrop={(e) => { e.preventDefault(); handleImage(e.dataTransfer.files[0]); }} onDragOver={(e) => e.preventDefault()} className="flex min-h-48 cursor-pointer flex-col items-center justify-center rounded-2xl border-2 border-dashed border-[#cce2d2] bg-[#f7fbf7] p-6 text-center" onClick={() => fileRef.current?.click()}><Upload className="mb-3 text-[#1c615d]" /><p className="font-bold text-[#173238]">اسحب الصورة هنا أو اخترها من جهازك</p><p className="mt-2 text-sm text-[#789094]">JPG، PNG، WebP — حتى 10 ميغابايت، والمعالجة محلية</p><input ref={fileRef} type="file" accept="image/*" className="hidden" onChange={(e) => handleImage(e.target.files?.[0])} />{fileName && <p className="mt-4 text-sm font-bold text-[#1c615d]">{fileName}</p>}{imageError && <p role="alert" className="mt-3 text-sm font-bold text-red-700">{imageError}</p>}</div>{imageUrl && <img src={imageUrl} alt="معاينة الصورة المختارة" className="max-h-64 w-full rounded-2xl object-contain" />}{slug === "image-resizer" && <div className="grid gap-3 sm:grid-cols-2"><label className="grid gap-2 text-sm font-bold">العرض<input type="number" min="1" value={width || ""} onChange={(e) => setWidth(Number(e.target.value))} className="rounded-xl border p-3" /></label><label className="grid gap-2 text-sm font-bold">الارتفاع<input type="number" min="1" value={height || ""} onChange={(e) => setHeight(Number(e.target.value))} className="rounded-xl border p-3" /></label></div>}{slug === "image-compressor" && <label className="grid gap-2 text-sm font-bold">الجودة: {Math.round(quality * 100)}%<input type="range" min="0.2" max="1" step="0.05" value={quality} onChange={(e) => setQuality(Number(e.target.value))} /></label>}{output && slug === "color-extractor" && <pre className="whitespace-pre-wrap rounded-2xl border bg-[#123f45] p-5 font-mono text-sm text-white">{output}</pre>}<div className="flex flex-wrap gap-3"><button onClick={() => slug === "color-extractor" ? extractColor() : processImage(slug === "jpg-to-png" ? "image/png" : slug === "image-to-webp" ? "image/webp" : "image/jpeg")} className="focus-ring inline-flex items-center gap-2 rounded-xl bg-[#123f45] px-5 py-3 font-bold text-white">{slug === "color-extractor" ? <><Palette size={17} /> استخراج اللون</> : <><Download size={17} /> معالجة وتنزيل</>}</button><button onClick={() => { setImageUrl(""); setFileName(""); setOutput(""); setImageError(""); }} className="focus-ring rounded-xl border px-5 py-3 font-bold text-[#607175]">إزالة</button></div></div>;
  const utility = slug === "password-generator" || slug === "uuid-generator";
  if (utility) return <div className="grid gap-5"><div className="rounded-2xl bg-[#edf5ef] p-5"><p className="text-sm leading-7 text-[#557174]">{slug === "password-generator" ? "توليد عشوائي آمن داخل المتصفح. لا يتم حفظ النتيجة." : "توليد UUID باستخدام مولد المتصفح المدمج."}</p></div><textarea value={output} readOnly placeholder="ستظهر النتيجة هنا" className="min-h-28 w-full rounded-2xl border bg-[#f7f8f4] p-4 font-mono text-sm outline-none" /><button onClick={slug === "password-generator" ? randomPassword : randomUuid} className="focus-ring inline-flex items-center justify-center gap-2 rounded-xl bg-[#123f45] px-5 py-3 font-bold text-white"><RefreshCw size={17} /> توليد نتيجة جديدة</button>{output && <button onClick={copy} className="focus-ring inline-flex items-center justify-center gap-2 rounded-xl border px-5 py-3 font-bold text-[#1c615d]"><Copy size={17} />{copied ? "تم النسخ" : "نسخ النتيجة"}</button>}</div>;
  return <div className="grid gap-4"><textarea value={value} onChange={(e) => setValue(e.target.value)} placeholder="اكتب أو الصق النص هنا..." className="min-h-48 w-full rounded-2xl border bg-[#f7f8f4] p-4 leading-7 outline-none focus:border-[#d9a947]" />{slug === "text-compare" && <textarea value={second} onChange={(e) => setSecond(e.target.value)} placeholder="النص الثاني للمقارنة..." className="min-h-32 w-full rounded-2xl border bg-[#f7f8f4] p-4 leading-7 outline-none focus:border-[#d9a947]" />}{(slug === "meta-checker") && <textarea value={second} onChange={(e) => setSecond(e.target.value)} placeholder="وصف الصفحة..." className="min-h-24 w-full rounded-2xl border bg-[#f7f8f4] p-4 leading-7 outline-none focus:border-[#d9a947]" />}{output && <pre className="whitespace-pre-wrap rounded-2xl border bg-[#123f45] p-5 font-mono text-sm leading-7 text-white">{output}</pre>}<div className="flex flex-wrap gap-3"><button onClick={runText} className="focus-ring inline-flex items-center gap-2 rounded-xl bg-[#123f45] px-5 py-3 font-bold text-white"><WandSparkles size={17} /> تشغيل الأداة</button>{output && <><button onClick={copy} className="focus-ring inline-flex items-center gap-2 rounded-xl border px-5 py-3 font-bold text-[#1c615d]"><Copy size={17} />{copied ? "تم النسخ" : "نسخ النتيجة"}</button><button onClick={() => download(new Blob([output], { type: "text/plain;charset=utf-8" }), `${slug}.txt`)} className="focus-ring inline-flex items-center gap-2 rounded-xl border px-5 py-3 font-bold text-[#1c615d]"><Download size={17} /> تنزيل</button></>}</div></div>;
}
